name: gps_speedo
description: "Ultra-lightweight GPS speedometer for Android split-screen usage."
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  # GPS and Location Services - Essential only
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true