name: gps_speedo
description: "Speedo - A Flutter application."
publish_to: 'none'

version: 2.2.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  # cupertino_icons: ^1.0.8
  # Probably no icons needed for now
  
  # GPS and Location Services - Essential only
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  
  # Keep screen awake during navigation
  wakelock_plus: ^1.2.8
  
  # Floating window overlay capability
  flutter_overlay_window: ^0.5.0
  
  # Bring app to foreground from background/overlay
  bg_launcher: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  
  fonts:
    - family: DIN1451Alt
      fonts:
        - asset: fonts/din1451alt.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon/speedo.png"